name: variance_modules
description: "Implementation of EIP-7579 modules"
version: 0.0.1
homepage: https://variance.space/
repository: https://github.com/vaariance/variance_modules
issue_tracker: https://github.com/vaariance/variance-modules/issues

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  variance_dart:
    git:
      url: https://github.com/vaariance/variance-dart.git
      ref: EIP-7579-safes
  web3_signers: ^0.1.9
  web3dart: ^2.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  build: ^2.4.2
