name: eip7579
description: "Dart Implementation of EIP-7579 (modular smart accounts by rhinestone.dev) using variance SDK"
version: 0.0.1
homepage: https://variance.space/
repository: https://github.com/vaariance/variance_modules
issue_tracker: https://github.com/vaariance/variance-modules/issues

environment:
  sdk: ^3.7.0
  flutter: ">=3.24.3"

platforms:
  android:
  ios:
  web:

dependencies:
  flutter:
    sdk: flutter
  variance_dart: 
    path: ../variance-dart
  web3_signers: ^0.2.1
  web3dart: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.15
  build: ^2.4.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

topics:
  - wallets
  - ERC4337
  - ERC7579
