name: variance_modules
description: "Implementation of EIP-7579 modules"
version: 0.0.1
homepage: https://variance.space/
repository: https://github.com/vaariance/variance_modules
issue_tracker: https://github.com/vaariance/variance-modules/issues

environment:
  sdk: ^3.7.0
  flutter: ">=3.24.3"

platforms:
  android:
  ios:
  web:

dependencies:
  flutter:
    sdk: flutter
  variance_dart: ^0.2.0
  web3_signers: ^0.2.0
  web3dart: ^2.7.3

dev_dependencies:
  build_runner: ^2.4.15
  build: ^2.4.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

topics:
  - ERC4337
  - ERC7579
